### ISSUE TITLE
테스트 작성을 위한 환경 설정

### ISSUE THREAD

**Issue by junhaesung** [depromeet/11th_7team_be#107]
## Feature Description
- SpringBootTest 사용하기 위한 환경설정

## Todo list
- [x] embedded database 추가 (h2)
- [x] embedded redis 추가
- [x] 사용하지 않는 dependency 제거 (aws java sdk cloud-information, ec2, kms 등)
- [x] 테스트 context 에서 사용할 yml 파일 추가

## References
- https://www.baeldung.com/spring-embedded-redis
