### ISSUE TITLE
domain 모듈에서 web 의존성 제거

### ISSUE THREAD

**Issue by junhaesung** [depromeet/11th_7team_be#124]
## Feature Description
- redirect view 관련 코드 
- member 에서 userdetails 상속 

## Todo list
- [ ] redirect view 관련 코드 web 으로 이동
- [ ] host 변수로 주입
- [ ] userdetails, userDetailService 사용하지 않음
