### ISSUE TITLE
로그 설정 개선

### ISSUE THREAD

**Issue by junhaesung** [depromeet/11th_7team_be#150]
## Feature Description
- 

## Todo list
- [ ] 컨테이너로 실행시 volume mouting 설정 추가
- [ ] tomcat access log 추가
- [ ] rolling policy 추가
